// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function ClearRecentFiles():Promise<void>;

export function ExportHTMLDialog(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetInitialFile():Promise<services.FileInfo>;

export function GetRecentFiles():Promise<Array<string>>;

export function GetStats(arg1:string):Promise<services.TextStats>;

export function OpenFile(arg1:string):Promise<services.FileInfo>;

export function OpenFileDialog():Promise<services.FileInfo>;

export function RenderMarkdown(arg1:string,arg2:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<services.FileInfo>;

export function SaveFileDialog(arg1:string,arg2:string):Promise<services.FileInfo>;

export function SetWindowTitle(arg1:string):Promise<void>;
